[tool.poetry]
name = "generative-art"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
py5 = "^0.10.1a1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
